//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecha
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string ArmoreType { get; set; }
        public string WeaponType { get; set; }
        public string EngineType { get; set; }
        public string Type { get; set; }
        public Nullable<int> SerialID { get; set; }
    }
}
