//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstMech_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core2
    {
        public int Id { get; set; }
        public string MechSystem { get; set; }
        public Nullable<int> Power { get; set; }
    }
}
