//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstMech_v2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lab1Entities : DbContext
    {
        public Lab1Entities()
            : base("name=Lab1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Core2> Core2 { get; set; }
        public virtual DbSet<Corpus> Corpora { get; set; }
        public virtual DbSet<Mecha> Mechas { get; set; }
        public virtual DbSet<Table2> Table2 { get; set; }
    }
}
